### ISSUE TITLE
ValidateToken failed to execute if an expired token is found

### ISSUE THREAD

**Issue by faina09** [DannyBoyNg/SimpleTokenService#1]
Ng.Services.SimpleTokenService.ValidateToken failed to execute if an expired token is found.

The reason is that you cannot remove an object from a collection during enumeration operation, i.e. cannot call `SimpleTokenRepo.Delete(token);` in the `foreach (var token in tokens)` loop.

Using the class **MyInMemorySimpleTokenRepository** provided in the README.md file you get a _System.InvalidOperationException_ with the message: "Collection was modified; enumeration operation may not execute."

Using a **database store** (I wrote) I found the error "There is already an open DataReader associated with this Connection which must be closed first."

**Comment by DannyBoyNg** [comment]
Collection modified issue is fixed with version 1.0.2. I'm still looking into the other issue.

**Comment by faina09** [comment]
great, this fix works for my database store implementation too!

But I guess you should use same fix in `GetMostRecent(int userId)` foreach loop too

**Comment by faina09** [comment]
if there is someone interested, this is a simple class to manage the tokens in a SqlServer Db Table:

```` c#
    internal class MySqlSimpleTokenRepository : ISimpleTokenRepository
    {
        protected readonly DbContext _myDbContext;
        private DbSet<SimpleSqlToken> SimpleTokenDbSet { get; set; }

        public MySqlSimpleTokenRepository()
        {
            string connectionString = "Data Source=.\\sqlexpress;Initial Catalog=MyDbName;Integrated Security=True";
            var options = GetOptions(connectionString);
            _myDbContext = new MyDbContext(options);
            SimpleTokenDbSet = _myDbContext.Set<SimpleSqlToken>();
        }

        public DbContextOptions<MyDbContext> GetOptions(string connectionString)
        {
            return SqlServerDbContextOptionsExtensions.UseSqlServer(new DbContextOptionsBuilder<MyDbContext>(), connectionString).Options;
        }

        public void Delete(ISimpleToken simpleToken)
        {
            var item = SimpleTokenDbSet.Where(x => x.Token == simpleToken.Token && x.UserId == simpleToken.UserId).SingleOrDefault();
            if (item != null) SimpleTokenDbSet.Remove(item);
            _myDbContext.SaveChanges();
        }

        public IEnumerable<ISimpleToken> GetByUserId(int userId)
        {
            return SimpleTokenDbSet.Where(x => x.UserId == userId);
        }

        public void Insert(int userId, string simpleToken)
        {
            SimpleTokenDbSet.Add(new SimpleSqlToken { UserId = userId, Token = simpleToken });
            _myDbContext.SaveChanges();
        }
    }

    public partial class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
        {
        }

        public virtual DbSet<SimpleSqlToken> SimpleSqlToken { get; set; }
    }

    [Table("SimpleToken")]
    public class SimpleSqlToken : ISimpleToken
    {
        [Key]
        public int Id { get; set; }
        public string Token { get; set; }
        public int UserId { get; set; }
    }
````

where the table used is created by 

````SQL
CREATE TABLE [dbo].[SimpleToken](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[Token] [varchar](250) NULL,
 CONSTRAINT [PK_SimpleToken] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
````

**Comment by DannyBoyNg** [comment]
Thanks @faina09 for the great code example. With your permission I would like to add it to the readme.md file.

I believe the other foreach in ` GetMostRecent(int userId) ` should work fine, because the collection/IEnumerable was already turned into a list before the foreach started. I will have to test a little more to be sure.

**Comment by faina09** [comment]
Of course you can use the code example as you want, it is based on your in-memory sample and works in my application.   
I close this issue because seems to be completely solved.

Thank you for this package and happy coding!
